### ISSUE TITLE
expression parsing for ompparser integration

### ISSUE THREAD

**Issue by yanyh15** [passlab/rexompiler#3]
We need a new set of grammar file (.ll and .yy) for bison and flex to parse expressions passed by ompparser. This can be done by starting deleting OMP-related token and grammar from omplexer.ll and ompparser.yy files from src/frontend/SageIII folder. The implementation should then export an interface, e.g. SgExpression * parse_expression( char* ) that is called by OmpAstConstruction when converting ompparser IR to Sage III IR. 

Create a new branch for this integration.

**Comment by ouankou** [comment]
The original OpenMP parser has been revised to an expression parser as planned.
* Lexer: https://github.com/passlab/rexompiler/blob/dev/src/frontend/SageIII/omp_exprparser_lexer.ll
* Parser: https://github.com/passlab/rexompiler/blob/dev/src/frontend/SageIII/omp_exprparser_parser.yy
* Fortran-specific helper (former Fortran OpenMP parser): https://github.com/passlab/rexompiler/blob/dev/src/frontend/SageIII/ompFortranParser.C
The Fortran helper is only used to iterate all the comments and preprocess the OpenMP comments, such as combining multiple lines into one. Currently, several Fortran helper functions are located in the AST constructor. Later on, they will be all moved to the Fortran-specific helper mentioned above.
