### ISSUE TITLE
Different compilers could generate transformed code in a different format

### ISSUE THREAD

**Issue by ouankou** [passlab/rexompiler#44]
Among our CI configurations, GCC 7 on Ubuntu 18.04 and GCC 9 on Ubuntu 20.04 generates identical transformed code. However, GCC 5 on Ubuntu 16.04 could produce different ones. So far, it has nothing to do with omp lowering but general C code.

According to the failed [CI test](https://github.com/passlab/rexompiler/actions/runs/343134259), lowering tests for `parallel.c` and `parallel-reduction.c` showed inconsistent results between the configurations. They are equivalent in semantic but written differently.

1. `parallel.c`

The upper part is generated by GCC 5 on Ubuntu 16.04. The affected code is the assertion.

https://github.com/passlab/rexompiler/blob/master/tests/nonsmoke/functional/CompileTests/OpenMP_tests/parallel.c

```c
<   _p_i == 100?((void )0) : __assert_fail("i == 100","parallel.c",9,__PRETTY_FUNCTION__);
<    *j == 77?((void )0) : __assert_fail("j == 77","parallel.c",10,__PRETTY_FUNCTION__);
---
>   (((void )(sizeof(((_p_i == 100?1 : 0))))) , ((
> {
>     if (_p_i == 100) 
>       ;
>      else 
>       __assert_fail("i == 100","parallel.c",9,__PRETTY_FUNCTION__);
>   })));
>   (((void )(sizeof((( *j == 77?1 : 0))))) , ((
> {
>     if ( *j == 77) 
>       ;
>      else 
>       __assert_fail("j == 77","parallel.c",10,__PRETTY_FUNCTION__);
>   })));
```

2. `parallel-reduction.c`

https://github.com/passlab/rexompiler/blob/master/tests/nonsmoke/functional/CompileTests/OpenMP_tests/parallel-reduction.c

```
<   sum == i * thread_num + 100?((void )0) : __assert_fail("sum == (i*thread_num + 100)","parallel-reduction.c",18,__PRETTY_FUNCTION__);
---
>   (((void )(sizeof(((sum == i * thread_num + 100?1 : 0))))) , ((
> {
>     if (sum == i * thread_num + 100) 
>       ;
>      else 
>       __assert_fail("sum == (i*thread_num + 100)","parallel-reduction.c",18,__PRETTY_FUNCTION__);
>   })));
```

There are a few options:

**1. Make the comparison of lowering code optional**

If users test REX compiler on the same two configurations, they can enable this option and expect all the tests are passed. Otherwise, they may end with a different lowering code, which doesn't mean the code is incorrect.
In our CI tests, the configuration of GCC 5 on Ubuntu 16.04 will not enable this comparison.

**2. Keep the comparison as the default option and omit the support to GCC 5 on Ubuntu 16.04**

We can explore how GCC 7+ works on Ubuntu 16.04.

**3. Deprecate the support to Ubuntu 16.04 completely**

The public official support of Ubuntu 16.04 has ended for quite a while, it makes sense to give up this OS. However, the upstream ROSE still supports the older versions. We may want to keep consistent with ROSE.

I recommend option 1 because users' compilers may behave differently anyway. If the comparison is required for testing, they may encounter false errors due to the format difference.

**Comment by yanyh15** [comment]
Let us choose option 1

**Comment by ouankou** [comment]
GitHub Actions will deprecate the support to Ubuntu 16.04 this September, so we don't test REX compiler on Ubuntu 16.04 anymore.
Currently, our CI tests only run on Ubuntu 18.04 and 20.04.

https://github.com/passlab/rexompiler/blob/dev/.github/workflows/auto_testing.yml

https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
