### ISSUE TITLE
Add ompparser as git submodule under frontend/SageIII/astOmpConstruction 

### ISSUE THREAD

**Issue by yanyh15** [passlab/rexompiler#6]
In this way, we do not need to include ompparser as a library dependency of the compiler. By default, git clone will pull ompparser files into that folder and we will also need to add Makefile/CMakeList.txt to make it build into librose.so. This is no priority, put here so we know we need to fix this later.

**Comment by ouankou** [comment]
Dr. Yan has addressed this issue in commits https://github.com/passlab/rexompiler/commit/21196e7a2a7fa8032b305bbbe1f89f4abe74caad, https://github.com/passlab/rexompiler/commit/0e5622812308e12155495d7064c5b205ba97efdf,
https://github.com/passlab/rexompiler/commit/60a4135754a81ff2550d3a0d05f859a62f1474b0.
