### ISSUE TITLE
Unique and meaningful symbol name for function and local variables introduced by the transformation

### ISSUE THREAD

**Issue by yanyh15** [passlab/rexompiler#66]
The symbol name should be both unique and meaningful. We can use __out_<file name including suffix>_<func_name>_<line number>_seq#_[<otherToMakesure if everything in the front are the same>]. We can change the outline function for generating the unique/meaningful symbol name.

**Comment by ouankou** [comment]
A suffix is added to the current generated function name, which is `__<enclosing function name>__<original line number>__`.
For example, the previous name `OUT__1__5599__` would be changed to `OUT__1__5599__main__6__`. It indicates the original OpenMP code is in the main function at line 10.

```c
#include <stdio.h>
#define N 1
#include "rex_kmp.h"
static void OUT__1__5599__main__6__(int *__global_tid,int *__bound_tid,void *__out_argv);

int main(int argc,char **argv)
{
  int __global_tid_main_6 = __kmpc_global_thread_num(0);
  int status = 0;
  int i = 1;
  if (i == 1)
    __kmpc_fork_call(0,1,OUT__1__5599__main__6__,0);
   else {
    OUT__1__5599__main__6__(&__global_tid_main_6,0,0);
  }
}

static void OUT__1__5599__main__6__(int *__global_tid,int *__bound_tid,void *__out_argv)
{
  int __global_tid_main_8 = __kmpc_global_thread_num(0);
  if (__kmpc_single(0,__global_tid_main_8)) {
    printf("Test\n");
    __kmpc_end_single(0,__global_tid_main_8);
  }
  __kmpc_barrier(0,__global_tid_main_8);
}
```

**Comment by ouankou** [comment]
It's fixed by commit https://github.com/passlab/rexompiler/commit/7bf7ea03b2ac6b6e9b603bacc1ce852602f12019.
