### ISSUE TITLE
ROSE does not have an API to generate GNU function attribute code

### ISSUE THREAD

**Issue by ouankou** [passlab/rexompiler#74]
To let a function to execute when the `main` function is started and exited, we need to use GNU function attribute `constructor/destructor`. However, ROSE does not support this syntax.
According to the [ROSE official document](http://rosecompiler.org/ROSE_HTML_Reference/classSgFunctionDeclaration.html), a function declaration supports a few other attribute syntax like `section`. However, even for this attribute, ROSE doesn't actually perform any transformation.

We may need to implement such kind of support from scratch in REX compiler including SgNode and corresponding transformation.

**Comment by yanyh15** [comment]
@ouankou constructor and destructor attribute is used in either the runtime code or in the code generated by the compiler. We do not need our compiler to recognize this syntax. We need gcc to compile the code that contains constructor and destructor.

**Comment by ouankou** [comment]
> @ouankou constructor and destructor attribute is used in either the runtime code or in the code generated by the compiler. We do not need our compiler to recognize this syntax. We need gcc to compile the code that contains constructor and destructor.

Sorry for the misleading description. I mean ROSE doesn't have an internal API to generate such kind of code.

**Comment by ouankou** [comment]
ROSE does have APIs to set up GNU function attributes. I went to the wrong document.
It should be: http://rosecompiler.org/ROSE_HTML_Reference/classSgFunctionModifier.html

The unparsing code is here:
https://github.com/passlab/rexompiler/blob/b26fbb355af31ce2c8e175a5127e11a4c88783ed/src/backend/unparser/languageIndependenceSupport/modified_sage.C#L2737

`__attribute__((constructor/destructor))` have been used to manage the GPU offloading environment in commit https://github.com/passlab/rexompiler/commit/90648c99cfa618d7994b77c38197fc95a855c597.
